services:
  nouveaubot:
    build:
      context: .
      args:
        APP_UID: ${UID:-1000}
        APP_GID: ${GID:-1000}
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - BOT_STATIC_PATH=/app/static
      - BOT_TOKEN
    volumes:
      - insightface_cache:/app/.insightface:rw

volumes:
  insightface_cache: