services:
  nouveaubot:
    build: .
    environment:
      - BOT_STATIC_PATH=/app/static
      - BOT_TOKEN
    volumes:
      - ./insightface_cache:/root/.insightface
      - ./ImageMagick-7/policy.xml:/etc/ImageMagick-7/policy.xml:ro
